name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        problem-matchers: true
        version: v1.59
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
      
    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...
  
    - name: Test & Coverage
      run: bash scripts/check_coverage.sh


    

